sudo: false
language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"

install:
  - npm install -g codecov npm
  - npm install

script:
  - npm test
  - npm run cover
